[platformio]
default_envs = heltec_wifi_lora_32_V3

[env:heltec_wifi_lora_32_V3]
platform = espressif32@6.13.0
board = heltec_wifi_lora_32_V3
framework = espidf
monitor_speed = 115200
extra_scripts = pre:tools/env_config.py
board_build.sdkconfig = sdkconfig.defaults
